benches/shootout-pidigits.rs
src/bigint.rs
src/complex.rs
src/integer.rs
src/iter.rs
src/lib.rs
src/rational.rs
src/traits.rs

A `_0` test fails, but don’t know why

Upgrade to latest Rust

---

src/bigint.rs

This commit implements `from_bytes` and `to_bytes` methods for `BigInt` and `BigUint`. These methods are very useful when working with BigInt types.
The current code works with big-endian slices/vectors, while the existing code (`new()` and `from_slice()`) uses little-endian slices/vectors. My opinion is that big-endian is preferable, but I can change this if necessary.

Implemented from_bytes and to_bytes

---

src/bigint.rs

As per https://github.com/rust-lang/rust/pull/23879.

Replace FromError with From

---

src/bigint.rs
src/complex.rs
src/integer.rs
src/iter.rs
src/lib.rs
src/rational.rs
src/traits.rs

Along the way, this commit also rationalizes the traits a bit more.
Moving to stable required vendoring a couple of minor things (notably,
radix formatting).
r? @alexcrichton

Update to 1.0.0-beta (stable only)

---

Cargo.toml
src/traits.rs

Closes #86 
Edit: also closes #88

Use latest rustc-serialize and rand, use correct version of from_str_radix, increment version for crates.io

---

src/traits.rs

Provide generic around f32/f64::MIN_POSITIVE

---

src/traits.rs

Added Sized trait bound for traits that requite it

---

src/complex.rs

In reference to #111.
The added methods are
* exp, ln, sqrt
* sin, cos, tan
* asin, acos, atan
* sinh, cosh, tanh
* asinh, acosh, atanh
I also wrote what I consider to be some pretty comprehensive tests for each of them.

Add mathematical functions for complex numbers.

---

src/rational.rs

Check for zero denominator when parsing Ratio

---

src/bigint.rs

Add a function that returns the sign of a BigInt.

---

src/complex.rs

Implement is_nan for the complex type

---

src/traits.rs

remove stale #[deriving(Zero)] docs

---

src/bigint.rs

* Make them take into account formatting parameters.
* ~~Make Debug match Display.~~

bigint: Improve fmt traits

---

src/lib.rs
traits/src/identities.rs
traits/src/lib.rs
traits/src/pow.rs
traits/src/sign.rs

Move functions remaining in num to num-traits

---

complex/src/lib.rs

Implement Default for Complex

---

rational/src/lib.rs

Cherry picked from #210 (minus the `new_raw` stuff), with small additions [in a third commit](https://github.com/rust-num/num/commit/32dee9a0c8259ee3846a644b3925bf981e261ada).

rational: recip bugfix and documentation tweaks

---

bigint/src/algorithms.rs

Just a couple of super minor cosmetic corrections.

Minor, style and comment typo

---

complex/src/lib.rs

complex: derive Eq

---

derive/Cargo.toml
derive/src/lib.rs
derive/tests/compile-fail/derive_on_struct.rs
derive/tests/compile-fail/enum_with_associated_data.rs
derive/tests/empty_enum.rs
derive/tests/trivial.rs
derive/tests/with_custom_values.rs

Fixes #251. Also includes a patch to get the tests working again.

macros 1.1 is now stable

---

bigint/Cargo.toml
bigint/LICENSE-APACHE
bigint/LICENSE-MIT
complex/Cargo.toml
complex/LICENSE-APACHE
complex/LICENSE-MIT
derive/Cargo.toml
derive/LICENSE-APACHE
derive/LICENSE-MIT
integer/Cargo.toml
integer/LICENSE-APACHE
integer/LICENSE-MIT
iter/Cargo.toml
iter/LICENSE-APACHE
iter/LICENSE-MIT
macros/Cargo.toml
macros/LICENSE-APACHE
macros/LICENSE-MIT
rational/Cargo.toml
rational/LICENSE-APACHE
rational/LICENSE-MIT
traits/Cargo.toml
traits/LICENSE-APACHE
traits/LICENSE-MIT

Add licenses to subcrates

---

integer/src/lib.rs

The implementation avoids overflows and fractions.

Implement binomial

---

README.md

Fixes https://github.com/rust-num/num-rational/issues/57

Add "fractions" to README.md

---

Cargo.toml
RELEASES.md

- Updated all sub-crates to their latest versions.
Resolves #433.

Release 0.4.2
