benches/shootout-pidigits.rs

I replaced most int refs with i32, and I used isize to hold the number
of default digits.

Replace deprecated int references with i32/isize.

---

benches/shootout-pidigits.rs

For the pi benchmark, I replaced the range function with the new range
syntax.

Remove range function.

---

src/bigint.rs

Without this rename, the library fails to compile on Rust master, since rust-lang/rust#21269 has landed.

Rename BigDigit module to big_digit

---

src/bigint.rs
src/lib.rs
src/rational.rs

This is a minimal set of changes to fix build errors and warnings.  More work could be done to convert other methods from Option to Result, and to use more error chaining.

Update to build with Rust 1.0.0-nightly

---

src/bigint.rs
src/lib.rs
src/rational.rs
src/traits.rs

Fixes compiler errors as of ~~latest nightly~~ Alpha 2.
There remain several warnings and it was necessary to comment out `#![cfg_attr(test, deny(warnings))]` on the crate as I wasn't sure of the best approach to fix this.
All tests pass on my machine.

Upgrade to latest Rust

---

src/lib.rs

The code was performing an extra squaring of the base, which might
trigger an arithmetic overflow that doesn't matter to the result.  Now
this squaring is only attempted when enough exp remains to need it.
A new doctest tries pow(6u8, 3), where an extra square would exceed 256.

pow: avoid unnecessary overflows

---

src/traits.rs

This commit brings in a load of unstable and/or deprecated traits from
the `std::num` module. These traits provide for some degree of generic
programming over numeric types. They are not stable in `std` mostly
because we want more time to iterate on their design. Moving them to the
`num` crate allows existing code to keep using this functionality as we
do so.
r? @alexcrichton 
Closes #74

Vendor deprecated/unstable traits from std::num

---

src/complex.rs

If `T` is an unsigned integer type, these methods are guaranteed to overflow unless the result is actually real, so we should disallow them for the same reason that `Neg` was removed from these types.

Require Neg for Complex conj and inv

---

src/bigint.rs

This commit converts instances of `<string literal>.as_bytes()` in the bigint doc examples to byte string literals. It also adds examples for `from_bytes_le()` and `to_bytes_be()`.

Improve bigint docs.

---

Cargo.toml
src/bigint.rs
src/integer.rs

Also incremented the crates.io version ready for the next `cargo publish`
This closes #84

Removed deprecation attributes that can no longer be used outside of std

---

src/traits.rs

For example, the following will print (4294967295, 65535):
extern crate num;
use num::traits::Bounded;
fn main() {
let t : (u32, u16) = Bounded::max_value();
println!("{:?}", t);
}

traits.rs: Implement Bounded for tuples of Bounded types

---

.gitignore
num_macros/Cargo.toml
num_macros/src/lib.rs
tests/test_macro.rs

This changes the name to `#[derive(NumFromPrimitive)]` in order to not conflict with the libsyntax macro.
If the general direction of this num library will supplant `std::num`, then I'd instead prefer to do the same trick we did for rustc-serialize, and have the compiler add a `#[derive(RustcFromPrimitive)]` that uses the trait in this crate instead.

Export the #[derive(FromPrimitive)] from rust proper

---

num-macros/src/lib.rs

Now compiling on `rustc 1.2.0-nightly (0cc99f9cc 2015-05-17) (built 2015-05-18)`

Update num-macros to rust master

---

src/lib.rs
src/traits.rs

Re-export `cast` for ergonomic reasons

---

num-macros/src/lib.rs

Now compiles with `rustc 1.2.0-nightly (0fc0476e6 2015-05-24) (built 2015-05-23)`

Update num-macros to rust nightly

---

.travis.yml
Cargo.toml
src/bigint.rs
src/complex.rs
src/lib.rs
src/rational.rs

Make rustc-serialize, bignum, rational, complex into opt-out features
Making bignum optional allows skipping the rustc-serialize and rand
dependencies too, and it makes a big difference in num's build time.
With default (all) features, clean build time including dependencies: 27
seconds.
With no default features, clean build time including dependencies (none):
5 seconds.
Fixes #63

Make rustc-serialize, bignum, rational, complex into opt-out features

---

src/complex.rs

Correct me if I'm wrong, but since the ```Float``` trait is defined as ```pub trait Float: Num + other_traits```, having ```impl<T: Clone + Float + Num> Complex<T>``` is not necessary and could be replaced with ```impl<T: Clone + Float> Complex<T>```.
I've moved the functions that are currently in the implementation of ```Complex<T: Clone + Float + Num>```, namely
- ```fn arg(&self) -> T```
- ```fn to_polar(&self) -> (T, T)```
- ```fn from_polar(r: &T, theta: &T) -> Complex<T>```
to the implementation of ```Complex<T: Clone + Float>```. Everything still builds/passes the tests.

Remove reduntant Num trait from an impl.

---

src/integer.rs

The binary gcd algorithm offers significant speedups when the CPU has a builtin instruction for counting trailing zeros.
I benched the improvements with random numbers. Code is at  https://github.com/Emerentius/gcd_bench . These are only rough measurements, I used 50 (Edit: Now 5000) number pairs for each. The old gcd liked to crash for `i8` when I used more.
These are the improvements on my machine (Intel i5 2500k). All numbers are averaged.
```
u8
gcd:            29.65 ns / call
binary_gcd:     20.70 ns / call (  43.2% faster )
u16
gcd:            58.66 ns / call
binary_gcd:     42.50 ns / call (  38.0% faster )
u32
gcd:            96.71 ns / call
binary_gcd:     72.13 ns / call (  34.1% faster )
u64
gcd:           314.31 ns / call
binary_gcd:    148.77 ns / call ( 111.3% faster )
i8 …
```

Implement Stein's algorithm for gcd

---

src/bigint.rs

Just fixing a compiler warning.  And making a similar fix inside example code.

Remove extra parentheses to fix a warning

---

src/complex.rs

Hello,
It might be handy to be able to perform basic arithmetic operations in expressions mixing complex numbers and numeric primitives; see #116. I would be grateful for any feedback, especially regarding the subsets of primitives for which certain operations are implemented.
Regards,
Ivan

Implement arithmetic with real for complex

---

benches/bigint.rs
benches/shootout-pidigits.rs
src/bigint.rs

I added add and subtract methods that take an operand by value, instead of by reference, so they can work in place instead of always allocating new BigInts for the result.
I'd like to hear if anyone knows a better way of doing this, though - with the various wrappers/forwardings doing this for all the operations is going to be a mess and add a ton of boilerplate. I haven't even tried to do a complete job of it yet.
I'm starting to think the sanest thing to do would be to only have in place implements of most of the operations - and have the wrappers clone() if necessary. That way, the only extra work we're doing is a memcpy(), which is a hell of a lot faster than a heap allocation.

[RFC] Some performance improvements

---

src/bigint.rs

From all primative unsigned ints to BigUint
From all primative ints to BigInt
From BigUint to BigInt
Closes: #117

bigint: add From implementations

---

src/bigint.rs

There cannot be any leading zeros in a BigUint so just derive Hash which will just hash the Vec directly.
Add Hash to Sign so we can derive it for BigInt as well.

bigint: simplify Hash

---

src/bigint.rs

The default implementations of to_f32, to_f64, from_32 and from_f64 are
limited to numbers fitting in i64 but BigInt can of course be much bigger.
The default to_f32 also has double rounding.
from_f32 and from_f64 have undefined behaviour if the float is too big to
fit in an i64.
This fixes these issues and keeps the rounding consistant with other float
to int conversions.
Also add ToBigUint and ToBigInt implementations for f32 and f64.
Currently this returns None if the BigInt is too big for to_f32 and to_f64 but it might make more sense to return Some(INFINITY) but I've decided to match f64::to_f32() for now.

bigint: fix float conversions

---

Cargo.toml
src/bigint.rs
src/lib.rs

Previously, the `rand` and `rustc-serialize` dependencies were optional
except they were required for the `bigint` feature.
Make the dependency on the `rand` crate optional in all cases.
including when the `bigint` feature is selected. Some of the tests for
the bigint feature are randomized so, while `rand` is now an optional
dependency, it is a non-optional dev-dependency.
Similarly, make the dependency on the `rustc-serialize` crate optional
in all cases, including when the `bigint` feature is selected.

Make `rand` and `rustc-serialize` dependencies optional.

---

src/bigint.rs

Before:
```
test fac_to_string     ... bench:       1,630 ns/iter (+/- 34)
test fib_to_string     ... bench:         359 ns/iter (+/- 11)
test to_str_radix_02   ... bench:       3,097 ns/iter (+/- 19)
test to_str_radix_08   ... bench:       1,146 ns/iter (+/- 38)
test to_str_radix_10   ... bench:       4,248 ns/iter (+/- 36)
test to_str_radix_16   ... bench:         881 ns/iter (+/- 44)
test to_str_radix_36   ... bench:       8,073 ns/iter (+/- 75)
```
After:
```
test fac_to_string     ... bench:       1,492 ns/iter (+/- 20)
test fib_to_string     ... bench:         368 ns/iter (+/- 7)
test to_str_radix_02   ... bench:       2,038 ns/iter (+/- 47)
test to_str_radix_08   ... bench:         812 ns/iter (+/- 9)
test to_str_radix_10   ... bench:       3,919 ns/iter (+/- 40)
test …
```

bigint: small to_str_radix optimization

---

src/bigint.rs

These were mysteriously missing from BigUint.

Add LowerHex and UpperHex formatting

---

src/bigint.rs

Is the testing for these enough? Any suggestions to improve them?

Add Binary, Octal to BigUint. Add UpperHex, LowerHex, Binary, Octal to BigInt

---

src/lib.rs

Implements a `checked_pow` function which does the same as `pow`, just with overflow checks.
And, similar to #152 and #153, the function uses references instead of cloning.
Adds a little macro to spare code repetition. Its scoped to the function so nothing gets polluted.

Add checked_pow function

---

num-macros/src/lib.rs

Fixes num_macros build for current nightly, broken by [this](https://github.com/rust-lang/rust/pull/31487/files) PR on rust.

Update num_macros to current nightly

---

src/integer.rs

Reorder ops in LCM to avoid overflow.
Fix #166

Reorder ops in LCM to avoid overflow.

---

src/rational.rs

Avoid overflows in Ratio's Ord::cmp

---

Cargo.toml
src/bigint.rs
src/complex.rs
src/lib.rs
src/rational.rs

Serde 0.7 dropped it's dependency on num, so this patch moves the implementations here. For the sake of a better implementation, this just serializes BigUint as a `Vec<u32>`, `BigInt` as a `(u8, Vec<u32>)`, `Complex<T>` as a `(T, T)`, and `Ratio<T>` as a `(T, T)`.

Add support for Serde 0.7.

---

rational/src/lib.rs

Zero is not positive or negative.
This was broken in 8be7e7bab5ffc7f998e713547b67c1a424d3b9b1.

Correct Ratio::is_negative and Ratio::is_positive

---

traits/src/cast.rs

Fix ToPrimitive for f64 -> f32 conversion.
It should use the destination type and not the source type to check if
the conversion would be to a value that's in range.
NOTE: A finite f64 value that is larger than the f32 value range now produces
None when converted to f32 with ToPrimitive.
Previously, too large f64 values would produce inf f32 values. This `as`
cast has an undefined result and was not specified to always produce for
example `inf`.
The conversion preserves nan/+-inf specifically.

Fix ToPrimitive for f64 -> f32 conversion.

---

complex/src/lib.rs

I would like to have a few functions added for complex numbers (powf, log and exp function with arbitrary base). I've provided an implementation with this commit. However it requires more work and discussion and I've added comments to point out the parts which I'm especially unhappy with. Would be nice to get some feedback so that we can improve this pull request first.

Added powc, powf, log and expf methods for complex numbers

---

bigint/src/lib.rs

When x.len() and y.len() are both equal and odd, we have x1.len() + y1.len() + 1
(the required size to multiply x1 and y1) > y.len() + 1
This fixes #187

bigint: Fix calculation of size for multiply temporaries

---

src/lib.rs

Rust 1.4 through 1.7 will issue warnings that `pub extern crate` does
not work as expected, although it appears to be fine.  But Rust 1.8 and
later issue `#[warn(private_in_public)]` for `pub use num_foo as foo` if
that crate isn't public, and that's headed toward a hard error.
@bluss suggested instead `pub mod foo { pub use num_foo::*; }`, which
I thought I had tried before, but it appears to work fine on all
versions of Rust.  Let's do it!
A small downside is that docs for `num::foo` now just show the wildcard
reexport, instead of direct documentation, but at least there's a link
to follow to the sub-crate.
It's a breaking change that `num::num_foo` paths are no longer public,
but we didn't really want those exposed in the first place.  I consider
this minor -- people should either use …

num: remove `pub` from sub-crates

---

complex/src/lib.rs

This PR fixes the compile error of `num-complex` that appears due to a redundant `use serde;` after `extern crate serde;` in the same module. To reproduce the error, just build `num-complex` with the feature `serde`, see below.
```zsh
% cargo build --features serde
Compiling num-complex v0.1.32 (file:///home/janis/github/num/complex)
src/lib.rs:27:5: 27:10 error: an extern crate named `serde` has already been imported in this module [E0259]
src/lib.rs:27 use serde;
^~~~~
src/lib.rs:19:1: 19:20 note: previous import of `serde` here
src/lib.rs:19 extern crate serde;
^~~~~~~~~~~~~~~~~~~
src/lib.rs:27:5: 27:10 help: run `rustc --explain E0259` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `num-complex`.
```

`use serde;` leads to compilation error; `extern crate` is enough

---

benches/bigint.rs
bigint/src/lib.rs

This splits the main arithmetic loops from the final carry/borrow
propagation, and also normalizes the slice lengths before iteration.
This lets the optimizer generate better code for these functions.

bigint: simplify the add2/sub2 loops

---

benches/bigint.rs
bigint/src/lib.rs

A new Fibonacci benchmark demonstrates the improvement by using both
addition and subtraction in each iteration of the loop, like #200.
Before:
test fib2_100          ... bench:       4,558 ns/iter (+/- 3,357)
test fib2_1000         ... bench:      62,575 ns/iter (+/- 5,200)
test fib2_10000        ... bench:   2,898,425 ns/iter (+/- 207,973)
After:
test fib2_100          ... bench:       1,973 ns/iter (+/- 102)
test fib2_1000         ... bench:      41,203 ns/iter (+/- 947)
test fib2_10000        ... bench:   2,544,272 ns/iter (+/- 45,183)

bigint: allow `Sub` to work in-place on the RHS

---

bigint/src/lib.rs

The patch "drop some dependencies on BigDigit's size" is the one I'd really like to get in.

Minor optimization, prep work for more optimization

---

traits/src/float.rs

To avoid a breaking change, these have crude default implementations as
well as better implementations for `f32` and `f64` in particular.  They
don't use the inherent methods though, because `f32` didn't stabilize
those until Rust 1.7.
Fixes #211

traits: add `to_degrees` and `to_radians` on `Float`

---

bigint/src/bigint.rs
bigint/src/biguint.rs
traits/src/bounds.rs
traits/src/float.rs
traits/src/int.rs
traits/src/lib.rs
traits/src/ops/saturating.rs

We already had `#[inline]` throughout a lot of the code, but notably some
functions which simply wrap inherent methods were not inlined.  That means
external references will get a full function call, when they could have been
optimized to as little as one opcode.
This PR inlines all functions that look tiny enough for this to matter.
Fixes #218.

Inline small functions, especially wrappers

---

traits/src/float.rs
traits/src/lib.rs

The pull request is to address issue #194. In order to keep the library organized, I’ve introduced a new trait for the new functionality. The trait is supposed to closely follows the [`consts`](https://doc.rust-lang.org/std/f64/consts/index.html) module from the standard library. There are at least the following three open questions:
1. What should the name of the trait be? Currently, it’s `Constant`; an alternative is `Consts`.
2. What should the names of the getters be? Currently, they are lower-case versions of the constants defined in the `consts` module. Note that `Float` provides `log2` and `log10`, whereas `LOG_2` and `LOG_10` get translated into `log_2` and `log_10`, respectively.
3. Should `Float` require the new trait? Or should it be left up to the user?
Please let me know what …

Add a trait for floating-point constants

---

.travis/test_nightly.sh
rational/src/lib.rs

Similar to #196 for num/complex, “use serde;” needed to be removed in num/rational.
Also, deserialization of `num/rational` needed to be fixed by adding type annotations.
This is in response to https://github.com/rust-num/num/pull/222#issuecomment-239957062 of issue https://github.com/rust-num/num/pull/222.
Also added a travis line, in response to https://github.com/rust-num/num/pull/222#issuecomment-239957062. Hope it works.

Fix import serde and rational deserialization

---

.travis/test_nightly.sh
bigint/Cargo.toml
complex/Cargo.toml
rational/Cargo.toml
rational/src/lib.rs

I updated `bigint`, `complex`, and `rational` to use `serde 0.8`, and also fixed deserialization and the `serde` feature as such in the `rational` crate (didn't add any tests, but it compiles now).
Similar to https://github.com/rust-num/num/pull/196 for `num/complex`, “`use serde;`” needed to be removed in `num/rational`.

Use serde 0.8

---

macros/src/lib.rs

Now compatible with rustc 1.13.0-nightly (32571c05c 2016-09-17)

Fix num-macros for nightly

---

traits/src/float.rs

Hey!
This PR exposes a new `epsilon` function in the `Float` trait so that users can access the `EPSILON` constant on the float types. I figured as this was such a minimal change it was easier to get a PR in offering the change then write up an issue.
For me this is a valuable addition. When writing linear algebra or other optimization routines with generic floats we often want to check if some stopping criteria is reached, often something like: `(a - b).abs() < eps`. Having access to a standard _small value_ would make this a little easier.

Implementing epsilon function to retrieve EPSILON constant

---

traits/src/int.rs

This use of `mut` was nonsensical for now, but is proposed to be
disallowed by rustc in the future (as a bugfix).
See rust-lang/rust/pull/37378 for context.

traits: Remove pattern in trait's method signature

---

bigint/src/lib.rs
complex/src/lib.rs
integer/src/lib.rs
iter/src/lib.rs
macros/src/lib.rs
rational/src/lib.rs
src/lib.rs
traits/src/lib.rs

Also update to use https instead of http. This avoids mixed content
degradation on docs.rs.
The doc root URLs are correct as they are, the URL does not include the
crate name itself.

Add doc(html_root_url) and other doc attrs to each crate

---

derive/src/lib.rs

Fix code duplication error

---

rational/src/lib.rs

Hi!
So I thought that this kind of trait would be useful when one wants to write code which should be generic over different types of numbers.

Added trait From<T> for Ratio<T> where T: Clone + Integer

---

rational/src/lib.rs

Right now it appears impossible to get integers without cloning them. Converting into a pair can be a cheap and easy way to extract the data.

rational: Into<(T,T)> implementation

---

rational/src/lib.rs

Fixes this warning with rustc nightly:
```
warning: attribute must be of the form: `#[should_panic]` or `#[should_panic(expected = "error message")]`
--> rational/src/lib.rs:1051:7
|
1051 |     #[should_panic = "== 0"]
|       ^^^^^^^^^^^^^^^^^^^^^
|
= note: Errors in this attribute were erroneously allowed and will become a hard error in a future release.
```

rational: test_recip_fail: Correct should_panic syntax

---

traits/src/lib.rs
traits/src/ops/mod.rs
traits/src/ops/wrapping.rs

Added `Wrapping` traits for the most common operations. Similar to the already present `Checked` traits.
It was quite strait-forward. I am unsure if the Handling of `Shl` / `Shr` is good. Their pattern is unfortunately a bit different than for the elementar mathematical operations by always taking `u32` as the RHS argument.
I just copied the docs from the stdlib. Is this ok license-wise?
Closes #255

Added traits for wrapping arithmetics.

---

src/lib.rs
traits/src/lib.rs

This PR adds a "clamp" function to num.  Oftentimes it is desirable to restrict a value to between a certain minimum and maximum, the clamp function provides a generic way to do this.

Add clamp function

---

bigint/src/bigint.rs
bigint/src/biguint.rs
bigint/src/tests/biguint.rs

If a `+` is encountered in the middle of parsing a BigUint, this should
generate an `ParseIntError::InvalidDigit`.  Since we can't create that
directly, we get it by trying to parse a `u64` from this point, but of
course `+` is a perfectly valid prefix to a `u64`.
Now we include the previous character in the string passed to `u64`, so it
has proper parsing context to understand what's in error.
Fixes #268.

bigint: Create the parsing error better for nested `+`

---

complex/src/lib.rs

This adds LowerExp and UpperExp traits for Complex, taking precision into account. Fixes #148

Add formatting options for Complex

---

integer/src/lib.rs

I'm not very happy with the excessive cloning, but to fix it the bounds on the type parameters would have to be excessive. We probably need something like [this](https://github.com/vks/discrete-log/blob/master/src/main.rs#L90) in `num-traits`.

Implement an iterator over the binomial coefficients

---

complex/src/lib.rs

Here's an ambitious proposal that puts currently practiced ffi usage of `Complex<f32/f64>` on sound footing.
Fixes  #79
Current users appear to be:
- https://crates.io/crates/blas
+ Their use is not about Complex<f64> in an extern function's signature, but it is explicitly using that it is memory layout compatible.

Complex: Use repr(C) and add documentation for what it means

---

traits/src/identities.rs
traits/src/lib.rs

Implemented Zero, One and Num for std::num::Wrapping<T>

---

traits/src/lib.rs

There are two new "utility" traits covering the basic operators:
`Add`, `Sub`, `Mul`, `Div`, and `Rem`.
- `NumOps<Rhs, Output>`: operators with an arbitrary operand and output.
- `NumAssignOps<Rhs>`: assignment operators with an arbitrary operand.
Then the new collection of numeric traits are:
- `Num`: effectively unchanged, just taking operands by value.
- `NumRef`: `Num` adding reference operands on the right side.
- `RefNum`: `&T` operators, with either `T` or `&T` on the right side.
- This does not specify `T: Num`, as rust-lang/rust#20671 means that
could only add a constraint, without implying its presence for use.
- `NumAssign`: `Num` adding assignment operators by value.
- `NumAssignRef`: `NumAssign` adding reference assignment operators.
- Nothing actually implements this yet! …

Add new traits for reference and assignment operators

---

bigint/src/lib.rs
complex/src/lib.rs
rational/src/lib.rs

`std::hash::SipHasher` is now deprecated, see https://doc.rust-lang.org/std/hash/struct.SipHasher.html

Replace deprecated Hasher

---

bigint/src/lib.rs
complex/src/lib.rs
rational/src/lib.rs

`DefaultHasher` wasn't stable until 1.13, at which point all the other
hashers were deprecated, so it's not easy for us to name a hasher type to
use for testing.  However, `RandomState` has been stable since 1.7, and it
implements `BuildHasher` that has a `Hasher` associated type.
(extends #287)

Get the default hasher indirectly

---

ci/test_full.sh
traits/Cargo.toml
traits/src/bounds.rs
traits/src/cast.rs
traits/src/float.rs
traits/src/identities.rs
traits/src/int.rs
traits/src/lib.rs
traits/src/ops/checked.rs
traits/src/ops/wrapping.rs
traits/src/pow.rs
traits/src/sign.rs

This makes it possible to build `traits` without `std`. For this a new
trait `BasicFloat` was introduced, implementing some basic functionality
that works with `core`. Most notably this is lacking functions like
`cos`, `sin`, etc.
`Float` is not available without `std`.
Refs #216.

traits: Introduce std feature

---

bigint/Cargo.toml
ci/test_full.sh
rational/src/lib.rs

- The CI script now tests them all with --no-default-features.
- bigint: testing needs rand even when the main feature is disabled.
- rational: gate `FromPrimitive for Ratio<BigInt>` on having bigint.

Test and fix subcrates with --no-default-features

---

traits/Cargo.toml
traits/src/bounds.rs
traits/src/cast.rs
traits/src/float.rs
traits/src/identities.rs
traits/src/int.rs
traits/src/lib.rs
traits/src/ops/checked.rs
traits/src/ops/wrapping.rs
traits/src/pow.rs
traits/src/sign.rs

This reverts commit 8b5d4ac24e6d1417359f684ccfde506838a7d2cc, reversing
changes made to ef752e46877dc163ec28ddcf4d71558c264bb78d.
See #297 -- it's a breaking change to feature-gate existing APIs.

Revert "Auto merge of #296 - vks:no_std, r=cuviper"

---

bigint/src/bigint.rs
bigint/src/tests/bigint.rs

This PR provides the methods `from_signed_bytes_le`, `from_signed_bytes_be`, `to_signed_bytes_le`, and `to_signed_bytes_be` to `BigInt`. This concern came around with [this SO question](https://stackoverflow.com/q/44345786/1233251), in which we realized that there was no readily available conversion from arrays in two's complement binary representation to a `BigInt`.
Please let me know what further changes should be made before it's good to go. In particular:
- Should the helper functions `twos_complement_(le|be)` go elsewhere? The algorithms module seems to be tied to `biguint` right now.
- The `from_...` methods currently require an extra copy by taking ownership of a `Vec<u8>`. Should this be avoided before it's merged?

Add BigInt two's complement conversions

---

bigint/Cargo.toml
bigint/src/bigint.rs
bigint/src/biguint.rs
ci/test_full.sh
complex/Cargo.toml
complex/src/lib.rs
rational/Cargo.toml
rational/src/lib.rs

W.r.t. https://github.com/rust-num/num/pull/302 & #218, I took the arrow to the knee and started changing what needed changing.
~~TODO:~~ Done; that was quicker than I thought.
Did I miss more `serde` stuff?

WIP: serde 1.0

---

traits/src/float.rs

These are the minimal assumptions to make about `NaN`. Fixes part of #312 (but not the `next` branch).

Fix float NaN positive/negative assumptions

---

rational/src/lib.rs

We can't use a derived `Hash` when we have a manual `Eq`, because we
need to uphold the invariant `a == b` → `h(a) == h(b)`.  Since `Eq`
doesn't require them to be in reduced form, `Hash` also needs to be
normalized.
Fixes #310.

rational: make sure Hash agrees with Eq

---

bigint/src/algorithms.rs
bigint/src/bigint.rs
bigint/src/biguint.rs
bigint/src/lib.rs
bigint/src/macros.rs
bigint/src/tests/bigint.rs
bigint/src/tests/biguint.rs

With my apologies for opening a new PR, and also for the 8 month delay, this continues the work started in #237 - the discussion there outlines the goals I was aiming for. I suppose this supersedes that PR and the other one can now be closed.
This PR adds support for Add, Sub, Mul, Div and Rem operations involving one BigInt/BigUint and one primitive integer, with operands in either order, and any combination of owned/borrowed arguments.

Scalar operations across all integer types

---

complex/src/lib.rs

Design choice: Use by-value forms of OpAssign and use Clone to forward the reference arguments. That matches what the other traits do (for example Add).
Design choice: The complex += complex operation needs Add, not just AddAssign. The complex += real operation can use just AddAssign. You could just use Add for both, not sure which way is preferable.

Implement OpAssign for Complex

---

complex/src/lib.rs

It's more efficient to implement these without creating an intermediate
complex value -- at the least, we don't have to rely on the compiler
optimizing out zero-ops.

complex: implement real ops directly

---

Cargo.toml

This adds the CI badge to the pages on crates.io, #323 adds it to the README. Sorry for the separate PRs, but I didn't feel like forking and cloning the repository down to my laptop and simply used the GitHub online editor instead :-)

Add CI badge

---

bigint/src/algorithms.rs
bigint/src/bigint.rs
bigint/src/biguint.rs
bigint/src/tests/bigint.rs
bigint/src/tests/biguint.rs

This commit implements `assign_from_slice(..)` for `BigUint` and `BigInt`. `assig_from_slice` is for performance : it allows to reassign a value to a `BigInt` or a `BigUint` without useless reallocations. It would be useful for loops for example. I need it to implement the Toom-3 algorithm.
I also added a missing test for `BigInt::from_slice(..)`.

Implement assign_from_slice

---

complex/src/lib.rs

This should address #209 with eyes towards addressing #321.
It was a little tricky to get `Rem` working for a general `Num`, and I had to add a `PartialOrd` constraint to get it working, but I think it should be fairly robust.
I could probably use extra eyes on the `from_str_radix` function, as I mostly lifted the code from the `from_str` function and I may be missing some subtleties in how that works.

Add general Rem and Num implementations for Complex<T>

---

benches/bigint.rs
bigint/src/algorithms.rs
bigint/src/bigint.rs

Hi !
I finally implemented the Toom-3 algorithm ! I first tried to minimize the memory allocations by allocating the `Vec<BigDigit>` myself, as was done for Toom-2, but Toom-3 needs more complex calculations, with negative numbers. So I gave up this method, to use `BigInt` directly, and it's already faster ! I also chose a better threshold for the Toom-2 algorithm.
Before any modification :
```
running 4 tests
test multiply_0        ... bench:         257 ns/iter (+/- 25)
test multiply_1        ... bench:      30,240 ns/iter (+/- 1,651)
test multiply_2        ... bench:   2,752,360 ns/iter (+/- 52,102)
test multiply_3        ... bench:  11,618,575 ns/iter (+/- 266,286)
```
With a better Toom-2 threshold (16 instead of 4) :
```
running 4 tests
test multiply_0        ... bench:         130 …
```

Optimizing BigUint and Bigint multiplication with the Toom-3 algorithm

---

traits/src/float.rs
traits/src/pow.rs

Resubmission of #153, since it wasn't open to maintainer edits.  I added a distinct `Float::powi` fallback since that doesn't have `Mul` by reference.
cc @dten

Use `Mul` by reference in `pow`

---

bigint/src/algorithms.rs
bigint/src/bigint.rs
bigint/src/biguint.rs
complex/src/lib.rs
iter/src/lib.rs
rational/src/lib.rs
traits/src/identities.rs

next: Add `is_one` method to `One` trait. 

---

bigint/src/bigint.rs
bigint/src/biguint.rs
complex/src/lib.rs

This makes formatting correct with the new pulldown-cmark Markdown parser (rust-lang/rust#44229).

Fix documentation formatting with commonmark enabled

---

benches/bigint.rs
bigint/src/algorithms.rs
bigint/src/biguint.rs
bigint/src/monty.rs
bigint/src/tests/biguint.rs

Based on this Gist: https://gist.github.com/yshui/027eecdf95248ea69606
Also adds support to `BigUint.from_str_radix()` for using `_` as a visual separator.
Closes #136

Implement modpow() for BigUint backed by Montgomery Multiplication

---

rational/src/lib.rs

We had a test for NaN already, but thanks to undefined casts (#119) it
was only passing by luck -- on armv7hl it failed:
https://bugzilla.redhat.com/show_bug.cgi?id=1511187
Now we check for NaN explicitly.

rational: check for NaN when approximating floats

---

bigint/src/biguint.rs

Changed the implementation of BigUint LCM from
`((self * other) / self.gcd(other))`
to
`self / self.gcd(other) * other`
The division is exact in both cases, so the result is the same, but the new code avoids the potentially-large intermediate product, speeding things up and using less memory.
I also removed the unnecessary parentheses, because I think it's clear what order everything will be executed in. But if others think differently I can add them back.

Avoid large intermediate product in LCM
